# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.box_check_update = false

	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", 512]
		vb.customize ["modifyvm", :id, "--cpus", 1]
	end

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "provision.yml"
		ansible.tags = [ "build" ]
		ansible.verbose = "#{ENV['VERBOSE']}" if ENV['VERBOSE']
	end
end
